export const FETCH_POKEMON = "FETCH_POKEMON"
export const ADD_TO_DEX = "ADD_TO_DEX"
export const REMOVE_FROM_DEX = "REMOVE_FROM_DEX"
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES"
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES"

